spring:
  application:
    name: db-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://ims-discovery-server.herokuapp.com/eureka/
  instance:
    hostname: ims-db-service.herokuapp.com