spring:
  application:
    name: db-service

eureka:
  client:
    serviceUrl:
      defaultZone: https://ims-discovery-server.herokuapp.com/eureka/
  instance:
    hostname: ims-discovery-server.herokuapp.com